#source 'https://github.com/CocoaPods/Specs'

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
#use_frameworks!

workspace 'ZWKeychainExample'

project './ZWKeychainExample'
target :ZWKeychainExample do
pod 'SAMKeychain', '~> 1.5.2'

  
end


